failure_msg_patterns = [
    "AssertionError: targets should not be none when in training mode",
    "AttributeError: 'NoneType' object has no attribute 'max'",
    "AttributeError: 'NoneType' object has no attribute 'passed'",
    "AssertionError",
    "datasets.exceptions.DatasetNotFoundError: Dataset 'imagenet-1k' is a gated dataset on the Hub. You must be authenticated to access it.",
    "EOFError: Ran out of input",
    "ModuleNotFoundError: No module named 'segmentation_models_pytorch'",
    "OSError: You are trying to access a gated repo.",
    "RuntimeError: Cannot find callable resnext101_64x4d in hubconf",
    "RuntimeError: Could not load libtorchcodec. Likely causes:",
    "RuntimeError: Error code: 13",
    "RuntimeError: The tensor has a non-zero number of elements, but its data is not allocated yet.",
    "RuntimeError: TT_FATAL @ ../tt_metal/impl/allocator/bank_manager.cpp:432: address.has_value()",
    "RuntimeError: TT_THROW @ ../tt_metal/impl/program/program.cpp:907: tt::exception",
    "RuntimeError: wget failed with exit code 256 when downloading",
    "TypeError: AutoShape.forward() takes from 2 to 5 positional arguments but 7 were given",
    "ValueError: Error code: 13",
    "ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])",
    "ValueError: Handler for MgpstrModelOutput did not return a torch.Tensor",
    "ValueError: No handler for class",
    "ValueError: You can only specify either r (8) or oft_block_size (32), but not both simultaneously, because r x oft_block_size == in_features.",
]